# Home directory structure configuration

[common]
# Directories common to all systems
dirs = [
  { path = ".config", mode = "0700" },
  { path = ".local/bin", mode = "0755" },
  { path = ".local/share", mode = "0755" },
  { path = ".ssh", mode = "0700" },
  { path = ".cache", mode = "0755" },
  { path = ".gnupg", mode = "0700" },
  { path = ".config/systemd/user", mode = "0755" },
  { path = "realms/cwiq/github", mode = "0755" },
  { path = "realms/rkx/gitlab", mode = "0755" },
]

[ubuntu]
# Ubuntu-specific directories
dirs = [
  { path = ".config/autostart", mode = "0755" },
]

[almalinux]
# AlmaLinux-specific directories
dirs = [
]