
[homebrew]
common = [
"aider",
"ansible",
"ansible-builder",
"ansible-cmdb",
"ansible-creator",
"ansible-lint",
"argc",
"bat",
"bitwarden-cli",
"chezmoi",
"cookiecutter",
"direnv",
"fd",
"fzf",
"fzf-make",
"git",
"git-lfs",
"gum",
"htop",
"jq",
"kcl-lang/tap/kcl",
"lnav",
"mani",
"node@22",
"rage",
"redo",
"ripgrep",
"skate",
"starship",
"the_silver_searcher",
"tmux",
"tree",
"uv",
"vim",
"yadm",
"yq",
]

ubuntu = [
"ncdu",
"macchina",
]

almalinux = [
"nmap",
"iftop",
]
