# move these to their own packages
# ---
# "aider",
# "ansible",
# "ansible-builder",
# "ansible-cmdb",
# "ansible-creator",
# "ansible-lint",
# "cookiecutter",
# "fzf",
# "fzf-make",
# "yadm",

[homebrew]
common = [
"argc",
"bat",
"bitwarden-cli",
"chezmoi",
"direnv",
"fd",
"git",
"git-lfs",
"gum",
"htop",
"jq",
"kcl-lang/tap/kcl",
"lnav",
"mani",
"node@22",
"rage",
"redo",
"ripgrep",
"skate",
"starship",
"the_silver_searcher",
"tmux",
"tree",
"uv",
"vim",
"yq",
]

ubuntu = [
"ncdu",
"macchina",
]

almalinux = [
"nmap",
"iftop",
]
