
[homebrew]
common = [
"bat",
"fd",
"git",
"htop",
"jq",
"ripgrep",
"starship",
"tmux",
"vim",
"ansible",
"ansible-builder",
"ansible-cmdb",
"ansible-creator",
"ansible-lint",
]

ubuntu = [
"tree",
"ncdu",
"neofetch",
]

almalinux = [
"tree",
"nmap",
"iftop",
]