
[homebrew]
common = [
"ansible",
"ansible-builder",
"ansible-cmdb",
"ansible-creator",
"ansible-lint",
"bat",
"bitwarden-cli",
"chezmoi",
"direnv",
"fd",
"git",
# "goredo",
"htop",
"jq",
"kcl-lang/tap/kcl",
"lnav",
"mani",
"redo",
"ripgrep",
"starship",
"the_silver_searcher",
"tmux",
"tree",
"uv",
"vim",
"yq",
]

ubuntu = [
"ncdu",
"macchina",
]

almalinux = [
"nmap",
"iftop",
]