
[homebrew]
common = [
"ansible",
"ansible-builder",
"ansible-cmdb",
"ansible-creator",
"ansible-lint",
"bat",
"chezmoi",
"direnv",
"fd",
"git",
"htop",
"jq",
"kcl-lang/tap/kcl",
"ripgrep",
"starship",
"the_silver_searcher",
"tmux",
"tree",
"vim",
]

ubuntu = [
"ncdu",
"neofetch",
]

almalinux = [
"nmap",
"iftop",
]