# secrets.toml
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
# .secrets/bitwarden
[secrets]
[secrets.bitwarden]
[secrets.bitwarden.base]
# .secrets/bitwarden/base/
# .secrets/bitwarden/base/ssh/
# .secrets/bitwarden/base/mani
[secrets.bitwarden.base.mani]
    files = ["mani.yaml"]
