# secrets.toml
# :::::::::::::::::::::::::::::::::::::::::::::::::::::::
# .secrets/bitwarden
[secrets]
[secrets.bitwarden]
[secrets.bitwarden.seed]
[secrets.bitwarden.seed.ssh]
    files = ["config", "id_rsa", "id_rsa.pub",]
[secrets.bitwarden.seed.mani]
    files = ["mani.yaml"]
[secrets.bitwarden.seed.assh]
    files = ["assh.yaml"]